pipeline {
   agent any



  stages {

   stage('checkout') {
     steps {
       checkout([$class: 'GitSCM',
          extensions: scm.extensions + [
         [$class: 'CleanBeforeCheckout'],
       ]
     ]
     }

  }

//  install npm and other modules required
   stage('Build') {
        steps {
        sh 'npm install'
      }
    }



  // do jest testing
    stage('test') {
      steps {
       sh 'npm install'
       sh 'npm test  --ci --reporters="jest-junit"'
       sh 'npx jest test  --coverage'
      }
    }


  // testing test
    stage('pubtest') {
     steps {
    junit 'reports/*.xml'

   }


  post {
          always {
              junit testResults: 'reports/*.xml'
          }
      }
    }
  //  android is built at this stage
     stage('mobilebuild') {
      steps {
       sh './jenkins/scripts/fastlanebeta.sh'
       echo 'app has ben successfully deployed to hockeyapp'
    }
   }





 //publish to npm repo
 stage('publish') {
    steps {
    sh 'source ~/.profile'
     sh 'source ~/.bash_profile'
    sh 'npm publish'
    }

 }

}




 }
