pipeline {
   agent any



  stages {
   stage('checkout') {
     steps {
       checkout scm
     }

  }


  // do jest testing
    stage('test') {
      steps {
       sh 'npm install'
       sh 'npm test -- --ci --testResultsProcessor="jest-junit"'
      }
    }



 // testing test
    stage('pubtest') {
     steps {
    junit 'reports/*.xml'


  }
 }


 //publish to npm repo
// stage('publish') {
//    steps {
 //    sh 'source ~/.profile'
//     sh 'source ~/.bash_profile'
//     sh 'npm publish'
//    }

// }

}
post {
        always {
            junit testResults: 'reports/*.xml'
        }
    }




 }
